name: 书旗小说
on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *'
jobs:
  build:
    runs-on: ubuntu-latest       
    steps:
      
      - name: Checkout
        run: |
          git clone https://github.com/QingAnLe/SQ.git ~/js
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          cd ~/js
          npm install
          npm install cron
          npm install request
          curl ipinfo.io/json
      - name: '【书旗小说】'
        run: |
          cd ~/js   
          node Task/shuqi.js
